services:
  # FastAPI backend
  backend:
    build: .
    container_name: backend
    command: "poetry run uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  # PostgreSQL database
  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # Redis cache for FastAPI-Limiter
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./redis-data:/data
