name: CI

on: [pull_request, workflow_dispatch]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: Lint
      run: ruff check

  test:
    name: Test frontend build
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd frontend && npm install

    - name: Test
      run: cd frontend && npm run build
